// <auto-generated />
using MerchantProfile.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerchantProfile.Api.Migrations
{
    [DbContext(typeof(MerchantDbContext))]
    [Migration("20240614164312_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MerchantProfile.Api.Models.Merchant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LinkWebsite")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = "69f5b439-4067-42f5-b9c6-dd63b4a7c5d2",
                            Address = "123 Main St, Anytown, USA",
                            Description = "First Merchant Description",
                            Email = "sample@gmail.com",
                            LinkWebsite = "http://www.merchantone.com",
                            Name = "Merchant One",
                            Password = "20ur290ur2ur824r2r2r2",
                            Phone = "123-456-7890",
                            Username = "hiepth123"
                        },
                        new
                        {
                            Id = "19c7cda1-95ad-4d09-9ffa-89143f6c21eb",
                            Address = "456 Elm St, Othertown, USA",
                            Description = "Second Merchant Description",
                            Email = "sample2@gmail.com",
                            LinkWebsite = "http://www.merchanttwo.com",
                            Name = "Merchant Two",
                            Password = "20ur290ur2ur8dd3d324r2r2r2",
                            Phone = "098-765-4321",
                            Username = "hiepth321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
