// <auto-generated />
using MerchantProfile.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerchantProfile.Api.Migrations
{
    [DbContext(typeof(MerchantDbContext))]
    [Migration("20240601013046_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MerchantProfile.Api.Models.Merchant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LinkWebsite")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("signature")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = "e9b10673-5bf5-4c7c-be43-49740b7c6395",
                            Address = "123 Main St, Anytown, USA",
                            Description = "First Merchant Description",
                            Email = "sample@gmail.com",
                            LinkWebsite = "http://www.merchantone.com",
                            Name = "Merchant One",
                            Password = "20ur290ur2ur824r2r2r2",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = "39ae71a3-1f29-4c5e-a0e8-12e06b70f7b5",
                            Address = "456 Elm St, Othertown, USA",
                            Description = "Second Merchant Description",
                            Email = "sample2@gmail.com",
                            LinkWebsite = "http://www.merchanttwo.com",
                            Name = "Merchant Two",
                            Password = "20ur290ur2ur8dd3d324r2r2r2",
                            Phone = "098-765-4321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
