// <auto-generated />
using MerchantProfile.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerchantProfile.Api.Migrations
{
    [DbContext(typeof(MerchantDbContext))]
    partial class MerchantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MerchantProfile.Api.Models.Merchant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LinkWebsite")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Merchants");

                    b.HasData(
                        new
                        {
                            Id = "bda30663-e042-40a8-94a4-9c6f2a21764b",
                            Address = "123 Main St, Anytown, USA",
                            Description = "First Merchant Description",
                            Email = "sample@gmail.com",
                            LinkWebsite = "http://www.merchantone.com",
                            Name = "Merchant One",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = "b51de648-7167-4360-ab8e-863bf3388ec0",
                            Address = "456 Elm St, Othertown, USA",
                            Description = "Second Merchant Description",
                            Email = "sample2@gmail.com",
                            LinkWebsite = "http://www.merchanttwo.com",
                            Name = "Merchant Two",
                            Phone = "098-765-4321"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
